apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-portal-flask-configmap
data:
  PORTAL_IMAGE: "{{ required "Portal Image é obrigatório, Preencha com 1, 2, ou 3" .Values.configmap.portalImage }}"