apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-portal-flask-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-portal-flask
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}